### ISSUE TITLE
Unable to use R expression for inheritance

### ISSUE THREAD

**Issue by RoelVerbelen** [jjallaire/config#38] opened 2021-09-03 21:35 UTC
Thanks for building this great package! 

I notice that using an R expression for the inherits field is currently not allowed:

```
shinyapps:
  inherits: !expr Sys.getenv("CONFIG")
  driver: 'PostgreSQL'
```

triggers an error for [these lines of `do_get()`](https://github.com/rstudio/config/blob/master/R/get.R#L83-L88):

```
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```

_Context_: Trying to use the config package to manage multiple shinyapps deployments (using different config settings for the application). I am exploring a setup in which I can specify the config setting of choice using an environment variable "CONFIG", but when deploying the shiny app to shinyapps.io I need to overwrite the driver setting (keeping all rest in occordance to selected config settings). 

Current workaround for my use case is to rather do something like this:
```
default:
  driver: !expr if ( Sys.getenv("R_CONFIG_ACTIVE") == "shinyapps" ) 'PostgreSQL' else 'PostgreSQL Unicode(x64)'
```

**Comment by andrie** [comment] 2021-09-19 18:56
Thanks for investigating.  I believe this is a duplicate of #9 and may be fixed by #36.

**Comment by andrie** [comment] 2023-08-29 07:17
Closing, since this was (probably) fixed in #36.  Please re-open with additional comments if there is more work to be done here.

**Comment by RoelVerbelen** [comment] 2023-09-03 06:46
Hi @andrie 

Thanks for the update. I just installed the latest version 0.3.2 in which I don't believe this issue is resolved. Here's a mininal example:

Define `test.yml` as
```
default:
  letter: 'a'

b:
  letter: 'b'

shinyapps:
  inherits: !expr Sys.getenv("CONFIG")
```

and then run

```
Sys.setenv("CONFIG" = "b")
config::get(file = "test.yml", config = "shinyapps")
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```

**Comment by andrie** [comment] 2023-09-03 14:44
Thank you, that's helpful.

I've pushed a potential fix to the dev branch.  Can you please check out the dev branch and tell me if it works for you?

**Comment by RoelVerbelen** [comment] 2023-09-04 00:21
That seems to have done the trick:

```
remotes::install_github("rstudio/config", ref = "dev")
Sys.setenv("CONFIG" = "b")
config::get(file = "test.yml", config = "shinyapps")
$letter
[1] "b"

$inherits
[1] "b"
```

**Closed as completed** 2023-09-04 05:02 UTC
Labels: feature

**Comment by andrie** [comment] 2023-09-04 05:06
Thank you.  I've now merged this into the main branch.

**Comment by RoelVerbelen** [comment] 2023-09-04 05:33
Thanks a lot!
