### ISSUE TITLE
Using config::get("my_config_value") in an expression in config.yaml

### ISSUE THREAD

**Issue by joiharalds** [jjallaire/config#9] opened 2017-08-25 16:43 UTC
This causes R to produce the error
`Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?`

and then get stuck in an infinite error producing loop with the error
`Error in yaml.load(paste(readLines(input, encoding = "UTF-8"), collapse = "\n"),  :`

This is not unexpected but it would be nicer if the `get` function could handle this situation and return `my_config_value` instead of producing an error. Better yet would be special syntax like `<my_config_value>` to tell `!expr` to look for this value in the same config.yaml file.

This feature might be overkill though.

**Comment by andrie** [comment] 2021-04-05 19:22
If this is still an issue, please can you add a reproducible example?

**Comment by dermcnor** [comment] 2021-04-20 23:19
Hi @andrie, I think that the code below reproduces what the op was asking... If not it reproduces something I'm looking for which matches the title 😄. In essence looking to reference values in the current yaml config.

``` R
yml <- 
'
default:
  trials: 5
  out_file: "out.csv"
  results: !expr file.path("dev/out", config::get("out_file"))
'

config_file <- tempfile("my_config", fileext = c(".yml"))
cat(yml, file = config_file)

config::get(file = config_file, use_parent = FALSE)
```

**Comment by andrie** [comment] 2021-04-21 12:26
Thanks for the reprex, @dermcnor 

I can now see what you're trying to do: cross-reference existing values in the yaml.

Right now this is not possible, as you've already identified.  By calling `config::get()` inside the config, you're setting up an infinite recursion, since every `config::get()` will re-evaluate the statement you're trying to resolve.

I guess the obvious solution is to use the config file only for variables that differ between installations, and then do the computation in your calling R script.

Can you please help me understand the use case where you need the computation directly inside the config file, rather than doing this elsewhere?

**Comment by dermcnor** [comment] 2021-04-21 14:07
Hey @andrie as we chatted about, my only real desire is for concatenating directories. Where `default` has user editable parameters, and then there are `dev` and `prod` configs for different servers. Hopefully this code better shows that. The first `get` works fine and the following two will fail as expected.

``` R
config_file <- tempfile("my_config", fileext = c(".yml"))

yml <- 
'
default:
  trials: 5
  out_file: "out.csv"
  
dev:
  out_dir: "dev/out"
  test: !expr file.path(out_dir, out_file)
  
prod:
  out_dir: "prod/out"
  test: !expr file.path(out_dir, out_file)
'

cat(yml, file = config_file)

config::get(file = config_file, use_parent = FALSE)
config::get(file = config_file, config = "dev", use_parent = FALSE)
config::get(file = config_file, config = "prod", use_parent = FALSE)
```

Additionally, I think that a minor change to `config::get()` can remedy the issue. It will allow to reference any defined values in the config that are not expressions.
Here's the original function in `config::get()`,

``` R
eval_recursively <- function(x) {
  is_expr <- vapply(x, is.expression, logical(1))
  x[is_expr] <- lapply(x[is_expr], eval, envir = baseenv())
  is_list <- vapply(x, is.list, logical(1))
  x[is_list] <- lapply(x[is_list], eval_recursively)
  x
}
```
and here is a modified version to allow access to defined values and works, at least on my simple example.

``` R
eval_recursively <- function(x) {
  is_expr <- vapply(x, is.expression, logical(1))
  new_env <- list2env(x[!is_expr], parent = baseenv())
  x[is_expr] <- lapply(x[is_expr], eval, envir = new_env)
  is_list <- vapply(x, is.list, logical(1))
  x[is_list] <- lapply(x[is_list], eval_recursively)
  x
}
```

**Comment by andrie** [comment] 2021-05-14 10:23
Re-opening, since this wasn't merged intentionally.  The proposed changes of #35 are now in the dev branch.

**Comment by joiharalds** [comment] 2022-06-27 15:07
https://github.com/rstudio/config/issues/9#issuecomment-823662423 is a correct reprex for the use case I was thinking of.

**Closed as completed** 2023-03-28 08:27 UTC
Labels: reprex
